name: CI
on:
  push:
  release:
    types: [published]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        toit-version: [ <sdk-version>, latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - uses: toitlang/action-setup@v1
        with:
          toit-version: ${{ matrix.toit-version }}
      - name: Test
        run: make test
